name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x ./free_disk_space.sh

      - name: Check free disk space
        run: ./free_disk_space.sh

      - run: echo "Running on GitHub-hosted runner"
