name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make free_disk_space.sh executable
        run: chmod +x .github/scripts/free_disk_space.sh

      - name: Run free_disk_space.sh script
        run: .github/scripts/free_disk_space.sh

      - run: echo "Running on GitHub-hosted runner"